### ISSUE TITLE
Function type variable and lazy stored properties not detected

### ISSUE THREAD

**Issue by Arthur111** [PaulTaykalo/swift-scripts#13]
You can define a function type variable or a lazy stored property and not using it and your script is blind.

[Lazy stored properties](https://docs.swift.org/swift-book/LanguageGuide/Properties.html)

[Function type variable](https://docs.swift.org/swift-book/LanguageGuide/Functions.html)

I do not think closing an active bug will solve the problem.

**Comment by PaulTaykalo** [comment]
Yep. 

Again. what exact case are you referencing to?

```
class A {
	lazy var item: String = ""
}
```
![image](https://user-images.githubusercontent.com/119268/45203537-325ab500-b285-11e8-9588-373ac8bfae53.png)


Will leave it here.
https://opensource.guide/how-to-contribute/#how-to-submit-a-contribution

**Comment by PaulTaykalo** [comment]
@Arthur111 is there any updates on this?

**Comment by Arthur111** [comment]
class A
{
    static let a = A()
}

class B
{
    lazy var c = A.a // you don't use c
}

c is not detected

class D
{
    var e: (()->())! // you don't use e
}

e is not detected

So as i said [Lazy stored properties](https://docs.swift.org/swift-book/LanguageGuide/Properties.html) and [Function type variable](https://docs.swift.org/swift-book/LanguageGuide/Functions.html) are not detected.

**Comment by Arthur111** [comment]
Issue not solved.
Some var are used and they are detected.
Some lazy var are not used and not detected.
Some functions var are used and detected.

In other words this script is not usable.

**Comment by PaulTaykalo** [comment]
@Arthur111 Sure, as soon as there'll be other examples, and some free time I will or will not try or not try to fix. If ever there were a chance for you to fix it. Wait...

**Comment by PaulTaykalo** [comment]
@Arthur111 https://github.com/PaulTaykalo/swift-scripts#known-issues
If you find any bug - feel free to open [pull request](https://github.com/PaulTaykalo/swift-scripts/pulls) with a fix.

**Comment by PaulTaykalo** [comment]
By the way, there are [Hacktoberfest](hacktoberfest.digitalocean.com) challenge at the moment, so there even more reasons to create a pull request,
