### ISSUE TITLE
Make output in xcode compatible format

### ISSUE THREAD

**Issue by iThinker** [PaulTaykalo/swift-scripts#4]
Although there are many false-positives, it would still be useful to produce warnings that can be picked up by xcode (if run for example as part of build phase). This way it is easier to process warnings.

**Comment by PaulTaykalo** [comment]
![image](https://user-images.githubusercontent.com/119268/32348473-88080ed2-c01c-11e7-9de6-762aeb195156.png)
![image](https://user-images.githubusercontent.com/119268/32348476-8af3a700-c01c-11e7-893f-013851568882.png)
